// examples/solid/src/components/Router.tsx
import { Router as RouterSolid } from 'reactive-route/solid';
import { useContext } from 'solid-js';

import { routes } from '../routes';
import { StoreContext } from './StoreContext';

export const Router = () => {
  const { routerStore } = useContext(StoreContext);

  return <RouterSolid routes={routes} routerStore={routerStore} />;
};

// examples/react-mobx/src/components/Router.tsx
import { useContext } from 'react';
import { Router as RouterMobx } from 'reactive-route/react';

import { routes } from '../routes';
import { StoreContext } from './StoreContext';

export function Router() {
  const { routerStore } = useContext(StoreContext);

  return <RouterMobx routes={routes} routerStore={routerStore} />;
}
