// examples/react/src/components/LinkPayload.tsx
import { TypePayload } from 'reactive-route';

import { TypeRoutesProject, useRouter } from '../router';

export function LinkPayload<TName extends keyof TypeRoutesProject>(props: {
  payload: TypePayload<TypeRoutesProject, TName>;
  className?: string;
  children?: any;
}) {
  const { router } = useRouter();

  const state = router.payloadToState(props.payload);

  return (
    <a
      href={state.url}
      className={props.className}
      onClick={(event) => {
        event.preventDefault();

        router.redirect(props.payload);
      }}
    >
      {props.children}
    </a>
  );
}

// examples/vue/src/components/LinkPayload.vue
<script setup lang="ts" generic="TName extends keyof TypeRoutesProject">
import { TypePayload } from 'reactive-route';
import { computed } from 'vue';

import { TypeRoutesProject, useRouter } from '../router';

const props = defineProps<{
  payload: TypePayload<TypeRoutesProject, TName>;
}>();

const { router } = useRouter();

const state = computed(() => router.payloadToState(props.payload));

const handleClick = (event: MouseEvent) => {
  event.preventDefault();

  void router.redirect(props.payload);
};
</script>

<template>
  <a :href="state.url" @click="handleClick">
    <slot />
  </a>
</template>
