// examples/solid/src/components/Router.tsx
import { Router as RouterSolid } from 'reactive-route/solid';
import { useContext } from 'solid-js';

import { routes } from '../routes';
import { StoreContext } from './StoreContext';

export const Router = () => {
  const { routerStore } = useContext(StoreContext);

  return <RouterSolid routes={routes} routerStore={routerStore} />;
};

// examples/preact/src/components/Router.tsx
import { useContext } from 'preact/hooks';
import { Router as RouterPreact } from 'reactive-route/preact';

import { routes } from '../routes';
import { StoreContext } from './StoreContext';

export function Router() {
  const { routerStore } = useContext(StoreContext);

  return <RouterPreact routes={routes} routerStore={routerStore} />;
}
