// packages/preact/Router.tsx
import { useEffect, useRef, useState } from 'preact/hooks';
import {
  handleComponentRerender,
  type PropsRouter,
  type TypeConfigsDefault,
  type TypeRouterLocal,
} from 'reactive-route';

function RouterInner<TConfigs extends TypeConfigsDefault>(props: PropsRouter<TConfigs>) {
  const [{ adapters }] = useState(() => props.router.getGlobalArguments());

  const disposerRef = useRef<() => void>(null);
  const ComponentRef = useRef<any>(null);

  const [localObservable] = useState<TypeRouterLocal>(() =>
    adapters.makeObservable({
      renderedName: undefined,
      props: {},
    })
  );

  useState(() => {
    handleComponentRerender(props, localObservable, (component) => {
      ComponentRef.current = component;
    });

    disposerRef.current = adapters.autorun(() =>
      handleComponentRerender(props, localObservable, (component) => {
        ComponentRef.current = component;
      })
    );
  });

  useEffect(
    () => () => {
      disposerRef.current?.();
    },
    []
  );

  if (!localObservable.renderedName || !ComponentRef.current) return null;

  return <ComponentRef.current {...localObservable.props} />;
}

export function Router<TConfigs extends TypeConfigsDefault>(props: PropsRouter<TConfigs>) {
  const [Component] = useState(() =>
    props.router.getGlobalArguments().adapters.observer!(RouterInner)
  );

  return <Component router={props.router} />;
}

// packages/solid2/Router.tsx
import { Dynamic } from '@solidjs/web2';
import {
  handleComponentRerender,
  type PropsRouter,
  type TypeConfigsDefault,
  type TypeRouterLocal,
} from 'reactive-route';
import { createSignal, onSettled, untrack } from 'solid-js2';

export function Router<TConfigs extends TypeConfigsDefault>(props: PropsRouter<TConfigs>): any {
  const { adapters } = untrack(() => props.router.getGlobalArguments());

  const localState: TypeRouterLocal = { renderedName: undefined };
  const [count, setCount] = createSignal(1, { ownedWrite: true });

  let ComponentRef: any;
  let componentPropsRef: Record<string, any> = {};

  const disposer = adapters.autorun(() =>
    handleComponentRerender(props, localState, (component, componentProps) => {
      ComponentRef = component;
      componentPropsRef = componentProps;

      if (typeof window !== 'undefined') setCount((value) => value + 1);
    })
  );

  if (typeof disposer === 'function') onSettled(() => disposer);

  return (
    <Dynamic
      component={count() > 0 ? ComponentRef! : undefined}
      {...(count() > 0 ? componentPropsRef : {})}
    />
  );
}
