// examples/simple_ssr/src/routerStore.tsx
import { observable, runInAction } from 'mobx';
import { createRouterStore } from 'reactive-route';

import { routes } from './routes';

export const getRouterStore = () =>
  createRouterStore({
    routes,
    batch: runInAction,
    routeError500: routes.error500,
    makeObservable: observable,
    replaceObject: (obj, newObj) => {
      runInAction(() => {
        for (const variableKey in obj) {
          if ((obj as Record<string, any>).hasOwnProperty(variableKey)) {
            delete obj[variableKey];
          }
        }
        Object.assign(obj as Record<string, any>, newObj);
      });

      return obj;
    },
  });

// examples/solid/src/routerStore.tsx
import { createRouterStore } from 'reactive-route';
import { batch, createRenderEffect } from 'solid-js';
import { createMutable, modifyMutable, produce } from 'solid-js/store';

import { routes } from './routes';

export function getRouterStore() {
  return createRouterStore({
    routes,
    batch,
    autorun: createRenderEffect,
    routeError500: routes.error500,
    makeObservable: createMutable,
    replaceObject: (obj, newObj) => {
      modifyMutable(
        obj,
        produce((state) => {
          if (typeof state === 'object' && state != null) {
            // biome-ignore lint/suspicious/useGuardForIn: false
            for (const variableKey in state) {
              delete state[variableKey];
            }
          }

          Object.assign(state || {}, newObj);
        })
      );
    },
  });
}
