// units/pages/vue/staticAutorun/StaticAutorun.vue
<template>StaticAutorun</template>

<script setup lang="ts">
import { useRouterStore } from '../useRouterStore';

const props = defineProps<{
  spy_pageRender: () => void;
  spy_pageAutorun: (arg: any) => void;
}>();

const { router } = useRouterStore();
const { adapters } = router.getGlobalArguments();

const currentRoute = router.state.staticRouteAutorun!;

props.spy_pageRender();

adapters.autorun(() => {
  props.spy_pageAutorun(currentRoute.name);
});
</script>

// units/pages/solid/StaticAutorun.tsx
import { useContext } from 'solid-js';

import { RouterContext } from './RouterContext';

export default function StaticAutorun(props: {
  spy_pageRender: () => void;
  spy_pageAutorun: (arg: any) => void;
}) {
  const { router } = useContext(RouterContext);

  props.spy_pageRender();

  router.getGlobalArguments().adapters.autorun(() => {
    props.spy_pageAutorun(router.state.staticRouteAutorun!.name);
  });

  return 'StaticAutorun';
}
