// examples/vue/src/components/LinkProps.vue
<script setup lang="ts" generic="TName extends keyof TypeConfigsProject">
import { TypePayload } from 'reactive-route';
import { computed } from 'vue';

import { TypeConfigsProject, useRouter } from '../router';

const props = defineProps<TypePayload<TypeConfigsProject, TName>>();

const { router } = useRouter();

const payload = computed(() => {
  return {
    name: props.name,
    query: (props as any).query,
    params: (props as any).params,
  } as TypePayload<TypeConfigsProject, TName>;
});

const state = computed(() => router.payloadToState(payload.value));

const handleClick = (event: MouseEvent) => {
  event.preventDefault();

  void router.redirect(payload.value);
};
</script>

<template>
  <a :href="state.url" @click="handleClick">
    <slot />
  </a>
</template>

// examples/react/src/components/LinkProps.tsx
import { TypePayload } from 'reactive-route';

import { TypeConfigsProject, useRouter } from '../router';

export function LinkProps<TName extends keyof TypeConfigsProject>(
  props: TypePayload<TypeConfigsProject, TName> & {
    className?: string;
    children?: any;
  }
) {
  const { router } = useRouter();

  const payload = {
    name: props.name,
    query: 'query' in props ? props.query : undefined,
    params: 'params' in props ? props.params : undefined,
  } as TypePayload<TypeConfigsProject, TName>;

  const state = router.payloadToState(payload);

  return (
    <a
      href={state.url}
      className={props.className}
      onClick={(event) => {
        event.preventDefault();

        router.redirect(payload);
      }}
    >
      {props.children}
    </a>
  );
}
